"""add donation carryforward

Revision ID: 06c547c69e24
Revises: 240a8128ab61
Create Date: 2026-08-29 03:28:16.123350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c547c69e24'
down_revision: Union[str, Sequence[str], None] = '240a8128ab61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_filings', sa.Column('donation_carryforward_out_cents', sa.BigInteger(), nullable=True))
    op.create_check_constraint('chk_filings_donation_carryforward_nonneg', 'tax_filings', 'donation_carryforward_out_cents IS NULL OR donation_carryforward_out_cents >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_filings_donation_carryforward_nonneg', 'tax_filings', type_='check')
    op.drop_column('tax_filings', 'donation_carryforward_out_cents')
    # ### end Alembic commands ###
