"""add capital income statements

Revision ID: 0dd2822bd625
Revises: c0a6f1bd5e3b
Create Date: 2026-08-29 03:08:17.041457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd2822bd625'
down_revision: Union[str, Sequence[str], None] = 'c0a6f1bd5e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_income_statements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.SmallInteger(), nullable=False),
    sa.Column('institution_name', sa.Text(), nullable=False),
    sa.Column('gross_income_cents', sa.BigInteger(), nullable=False),
    sa.Column('kapitalertragsteuer_withheld_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('solidarity_surcharge_withheld_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('church_tax_withheld_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('church_tax_withheld_cents >= 0', name='chk_capital_income_church_nonneg'),
    sa.CheckConstraint('gross_income_cents >= 0', name='chk_capital_income_gross_nonneg'),
    sa.CheckConstraint('kapitalertragsteuer_withheld_cents >= 0', name='chk_capital_income_kapest_nonneg'),
    sa.CheckConstraint('solidarity_surcharge_withheld_cents >= 0', name='chk_capital_income_soli_nonneg'),
    sa.CheckConstraint('tax_year BETWEEN 2015 AND 2100', name='chk_capital_income_tax_year'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_capital_income_user_year', 'capital_income_statements', ['user_id', 'tax_year'], unique=False)
    op.add_column('tax_filings', sa.Column('capital_gains_tax_cents', sa.BigInteger(), nullable=True))
    op.add_column('tax_filings', sa.Column('capital_gains_soli_cents', sa.BigInteger(), nullable=True))
    op.add_column('tax_filings', sa.Column('capital_gains_church_tax_cents', sa.BigInteger(), nullable=True))
    op.create_check_constraint('chk_filings_capital_gains_church_tax_nonneg', 'tax_filings', 'capital_gains_church_tax_cents IS NULL OR capital_gains_church_tax_cents >= 0')
    op.create_check_constraint('chk_filings_capital_gains_soli_nonneg', 'tax_filings', 'capital_gains_soli_cents IS NULL OR capital_gains_soli_cents >= 0')
    op.create_check_constraint('chk_filings_capital_gains_tax_nonneg', 'tax_filings', 'capital_gains_tax_cents IS NULL OR capital_gains_tax_cents >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_filings_capital_gains_tax_nonneg', 'tax_filings', type_='check')
    op.drop_constraint('chk_filings_capital_gains_soli_nonneg', 'tax_filings', type_='check')
    op.drop_constraint('chk_filings_capital_gains_church_tax_nonneg', 'tax_filings', type_='check')
    op.drop_column('tax_filings', 'capital_gains_church_tax_cents')
    op.drop_column('tax_filings', 'capital_gains_soli_cents')
    op.drop_column('tax_filings', 'capital_gains_tax_cents')
    op.drop_index('idx_capital_income_user_year', table_name='capital_income_statements')
    op.drop_table('capital_income_statements')
    # ### end Alembic commands ###
