"""add kinderfreibetrag guenstigerpruefung fields

Revision ID: 240a8128ab61
Revises: 279e32e1017f
Create Date: 2026-08-29 03:20:27.507451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240a8128ab61'
down_revision: Union[str, Sequence[str], None] = '279e32e1017f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_filings', sa.Column('number_of_children', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('tax_filings', sa.Column('kindergeld_received_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('tax_filings', sa.Column('kinderfreibetrag_applied', sa.Boolean(), nullable=True))
    op.add_column('tax_filings', sa.Column('kinderfreibetrag_total_cents', sa.BigInteger(), nullable=True))
    op.create_check_constraint('chk_filings_children_nonneg', 'tax_filings', 'number_of_children >= 0')
    op.create_check_constraint('chk_filings_kinderfreibetrag_nonneg', 'tax_filings', 'kinderfreibetrag_total_cents IS NULL OR kinderfreibetrag_total_cents >= 0')
    op.create_check_constraint('chk_filings_kindergeld_nonneg', 'tax_filings', 'kindergeld_received_cents >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_filings_kindergeld_nonneg', 'tax_filings', type_='check')
    op.drop_constraint('chk_filings_kinderfreibetrag_nonneg', 'tax_filings', type_='check')
    op.drop_constraint('chk_filings_children_nonneg', 'tax_filings', type_='check')
    op.drop_column('tax_filings', 'kinderfreibetrag_total_cents')
    op.drop_column('tax_filings', 'kinderfreibetrag_applied')
    op.drop_column('tax_filings', 'kindergeld_received_cents')
    op.drop_column('tax_filings', 'number_of_children')
    # ### end Alembic commands ###
