"""add onboarding profile fields

Revision ID: 26ed37e281a2
Revises: 06c547c69e24
Create Date: 2026-08-29 19:24:21.682171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ed37e281a2'
down_revision: Union[str, Sequence[str], None] = '06c547c69e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('street', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('house_number', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('steuernummer', sa.Text(), nullable=True))
    op.create_check_constraint('chk_users_postal_code_format', 'users', "postal_code IS NULL OR postal_code ~ '^\\d{5}$'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_users_postal_code_format', 'users', type_='check')
    op.drop_column('users', 'steuernummer')
    op.drop_column('users', 'city')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'house_number')
    op.drop_column('users', 'street')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
