"""add self employment statements

Revision ID: 279e32e1017f
Revises: 8e8a28386358
Create Date: 2026-08-29 03:15:15.123984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279e32e1017f'
down_revision: Union[str, Sequence[str], None] = '8e8a28386358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_employment_statements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.SmallInteger(), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('gross_revenue_cents', sa.BigInteger(), nullable=False),
    sa.Column('deductible_expenses_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deductible_expenses_cents >= 0', name='chk_self_employment_expenses_nonneg'),
    sa.CheckConstraint('gross_revenue_cents >= 0', name='chk_self_employment_revenue_nonneg'),
    sa.CheckConstraint('tax_year BETWEEN 2015 AND 2100', name='chk_self_employment_tax_year'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_self_employment_user_year', 'self_employment_statements', ['user_id', 'tax_year'], unique=False)
    op.add_column('tax_filings', sa.Column('net_self_employment_income_cents', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_filings', 'net_self_employment_income_cents')
    op.drop_index('idx_self_employment_user_year', table_name='self_employment_statements')
    op.drop_table('self_employment_statements')
    # ### end Alembic commands ###
