"""add rental property statements

Revision ID: 8e8a28386358
Revises: 0dd2822bd625
Create Date: 2026-08-29 03:12:31.842462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8a28386358'
down_revision: Union[str, Sequence[str], None] = '0dd2822bd625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_property_statements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.SmallInteger(), nullable=False),
    sa.Column('property_address', sa.Text(), nullable=False),
    sa.Column('gross_rental_income_cents', sa.BigInteger(), nullable=False),
    sa.Column('deductible_expenses_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deductible_expenses_cents >= 0', name='chk_rental_property_expenses_nonneg'),
    sa.CheckConstraint('gross_rental_income_cents >= 0', name='chk_rental_property_income_nonneg'),
    sa.CheckConstraint('tax_year BETWEEN 2015 AND 2100', name='chk_rental_property_tax_year'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rental_property_user_year', 'rental_property_statements', ['user_id', 'tax_year'], unique=False)
    op.add_column('tax_filings', sa.Column('net_rental_income_cents', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_filings', 'net_rental_income_cents')
    op.drop_index('idx_rental_property_user_year', table_name='rental_property_statements')
    op.drop_table('rental_property_statements')
    # ### end Alembic commands ###
