"""initial schema

Recreates the schema previously hand-written in db/schema.sql (now a
frozen historical reference -- this migration is the authoritative
source of truth going forward). Everything below the `# ### commands
auto generated by Alembic ###` markers came from
`alembic revision --autogenerate` against the SQLAlchemy models in
app/models/; the extension and trigger blocks were added by hand
immediately after, since neither is representable in SQLAlchemy metadata.

Revision ID: c0a6f1bd5e3b
Revises:
Create Date: 2026-08-29 02:47:42.111054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0a6f1bd5e3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Table -> trigger name, matching db/schema.sql's naming exactly (note
# tax_filings' trigger is trg_filings_updated_at, NOT
# trg_tax_filings_updated_at -- an explicit mapping avoids that mismatch
# recurring if another mutable table is added later).
_UPDATED_AT_TRIGGERS = {
    "users": "trg_users_updated_at",
    "deductions": "trg_deductions_updated_at",
    "tax_filings": "trg_filings_updated_at",
}


def upgrade() -> None:
    """Upgrade schema."""
    # --- hand-added: extensions must exist before any table uses UUID
    # defaults (pgcrypto's gen_random_uuid()) or the CITEXT column type. ---
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('tax_identification_number', sa.Text(), nullable=True),
    sa.Column('residence_state', sa.Enum('BADEN_WUERTTEMBERG', 'BAYERN', 'BERLIN', 'BRANDENBURG', 'BREMEN', 'HAMBURG', 'HESSEN', 'MECKLENBURG_VORPOMMERN', 'NIEDERSACHSEN', 'NORDRHEIN_WESTFALEN', 'RHEINLAND_PFALZ', 'SAARLAND', 'SACHSEN', 'SACHSEN_ANHALT', 'SCHLESWIG_HOLSTEIN', 'THUERINGEN', name='federal_state_enum'), nullable=False),
    sa.Column('tax_class', sa.Enum('I', 'II', 'III', 'IV', 'V', 'VI', name='tax_class_enum'), server_default='I', nullable=False),
    sa.Column('church_tax_type', sa.Enum('NONE', 'ROEMISCH_KATHOLISCH', 'EVANGELISCH', 'OTHER', name='church_tax_type_enum'), server_default='NONE', nullable=False),
    sa.Column('is_joint_assessment', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('spouse_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tax_identification_number IS NULL OR tax_identification_number ~ '^\\d{11}$'", name='chk_steuer_id_format'),
    sa.ForeignKeyConstraint(['spouse_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('deductions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.SmallInteger(), nullable=False),
    sa.Column('category', sa.Enum('COMMUTE', 'HOME_OFFICE', 'WORK_EQUIPMENT', 'FURTHER_EDUCATION', 'DOUBLE_HOUSEHOLD', 'INSURANCE', 'DONATIONS', 'CHILDCARE', 'HANDWERKERLEISTUNGEN', 'OTHER', name='deduction_category_enum'), nullable=False),
    sa.Column('amount_claimed_cents', sa.BigInteger(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_claimed_cents IS NULL OR amount_claimed_cents >= 0', name='chk_deductions_amount_nonneg'),
    sa.CheckConstraint('tax_year BETWEEN 2015 AND 2100', name='chk_deductions_tax_year'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deductions_details_gin', 'deductions', ['details'], unique=False, postgresql_using='gin')
    op.create_index('idx_deductions_user_year_category', 'deductions', ['user_id', 'tax_year', 'category'], unique=False)
    op.create_table('tax_filings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'FEE_PAID', 'SUBMITTED', 'ACCEPTED', 'REJECTED', name='filing_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('estimated_refund_cents', sa.BigInteger(), nullable=True),
    sa.Column('taxable_income_cents', sa.BigInteger(), nullable=True),
    sa.Column('income_tax_cents', sa.BigInteger(), nullable=True),
    sa.Column('solidarity_surcharge_cents', sa.BigInteger(), nullable=True),
    sa.Column('church_tax_cents', sa.BigInteger(), nullable=True),
    sa.Column('tax_credits_applied_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('processing_fee_cents', sa.BigInteger(), server_default=sa.text('3490'), nullable=False),
    sa.Column('fee_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_provider_ref', sa.Text(), nullable=True),
    sa.Column('elster_transfer_ticket', sa.Text(), nullable=True),
    sa.Column('elster_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elster_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elster_rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('church_tax_cents IS NULL OR church_tax_cents >= 0', name='chk_filings_church_tax_nonneg'),
    sa.CheckConstraint('income_tax_cents IS NULL OR income_tax_cents >= 0', name='chk_filings_income_tax_nonneg'),
    sa.CheckConstraint('solidarity_surcharge_cents IS NULL OR solidarity_surcharge_cents >= 0', name='chk_filings_soli_nonneg'),
    sa.CheckConstraint('tax_credits_applied_cents >= 0', name='chk_filings_credits_nonneg'),
    sa.CheckConstraint('tax_year BETWEEN 2015 AND 2100', name='chk_filings_tax_year'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tax_year', name='uq_filings_user_year')
    )
    op.create_index('idx_filings_status', 'tax_filings', ['status'], unique=False)
    op.create_table('wage_tax_certificates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.SmallInteger(), nullable=False),
    sa.Column('employer_name', sa.Text(), nullable=False),
    sa.Column('employer_tax_number', sa.Text(), nullable=True),
    sa.Column('gross_wage_cents', sa.BigInteger(), nullable=False),
    sa.Column('income_tax_withheld_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('solidarity_surcharge_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('church_tax_withheld_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('pension_insurance_employee_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('health_insurance_employee_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('long_term_care_insurance_employee_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('unemployment_insurance_employee_cents', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('church_tax_withheld_cents >= 0', name='chk_wtc_church_tax_nonneg'),
    sa.CheckConstraint('gross_wage_cents >= 0', name='chk_wtc_gross_wage_nonneg'),
    sa.CheckConstraint('health_insurance_employee_cents >= 0', name='chk_wtc_health_nonneg'),
    sa.CheckConstraint('income_tax_withheld_cents >= 0', name='chk_wtc_income_tax_nonneg'),
    sa.CheckConstraint('long_term_care_insurance_employee_cents >= 0', name='chk_wtc_ltc_nonneg'),
    sa.CheckConstraint('pension_insurance_employee_cents >= 0', name='chk_wtc_pension_nonneg'),
    sa.CheckConstraint('solidarity_surcharge_cents >= 0', name='chk_wtc_soli_nonneg'),
    sa.CheckConstraint('tax_year BETWEEN 2015 AND 2100', name='chk_wtc_tax_year'),
    sa.CheckConstraint('unemployment_insurance_employee_cents >= 0', name='chk_wtc_unemployment_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wtc_user_year', 'wage_tax_certificates', ['user_id', 'tax_year'], unique=False)
    # ### end Alembic commands ###

    # --- hand-added: updated_at auto-touch trigger, applied to the three
    # mutable tables (wage_tax_certificates is insert/delete-only, no
    # updated_at column, so it's excluded -- matches schema.sql). ---
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table_name, trigger_name in _UPDATED_AT_TRIGGERS.items():
        op.execute(
            f"""
            CREATE TRIGGER {trigger_name} BEFORE UPDATE ON {table_name}
                FOR EACH ROW EXECUTE FUNCTION set_updated_at();
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    # --- hand-added: reverse of the trigger block above, before the
    # tables (and thus the function's dependents) are dropped. ---
    for table_name, trigger_name in _UPDATED_AT_TRIGGERS.items():
        op.execute(f"DROP TRIGGER IF EXISTS {trigger_name} ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wtc_user_year', table_name='wage_tax_certificates')
    op.drop_table('wage_tax_certificates')
    op.drop_index('idx_filings_status', table_name='tax_filings')
    op.drop_table('tax_filings')
    op.drop_index('idx_deductions_user_year_category', table_name='deductions')
    op.drop_index('idx_deductions_details_gin', table_name='deductions', postgresql_using='gin')
    op.drop_table('deductions')
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###

    # --- hand-added: Postgres ENUM types are NOT automatically dropped
    # when the table(s) using them are dropped (confirmed empirically --
    # `op.drop_table` alone leaves them behind, which then breaks a
    # subsequent `upgrade head` with "type already exists"). Drop them
    # explicitly, after every table that references them is gone. ---
    for enum_name in (
        "federal_state_enum",
        "tax_class_enum",
        "church_tax_type_enum",
        "deduction_category_enum",
        "filing_status_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # --- hand-added: extensions are left in place deliberately (not
    # dropped here) -- other schemas/databases on the same Postgres
    # instance may depend on pgcrypto/citext, and dropping a shared
    # extension from an application-level migration is not this
    # migration's call to make. ---
